Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.synced_folder "../", "/home/vagrant/sre-lab", create: true
  config.vm.hostname = "dayaMB"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"  # 8GB RAM
    vb.cpus = 8
    vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provision "shell", path: "setup-docker-k3d-kubectl.sh"
  config.vm.provision "shell", path: "setup-vagrant-virtualbox.sh"
end

