Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop"
  config.vm.box_version = "2506.0.0"

  config.vm.synced_folder "../", "/home/vagrant/sre-lab", create: true
  config.vm.hostname = "dayaMB"

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provision "shell", path: "setup-docker-k3d-kubectl.sh"
  config.vm.provision "shell", path: "setup-vagrant-virtualbox.sh"
end

