apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  namespace: dev
  labels:
    app: my-flask-app  
spec:
  selector:
    app: my-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
